alias nv='nvim'
alias rm='trash'
alias restore='trash-restore'
alias ls='eza -l --header --group-directories-first --icons=auto --git'
alias cat='bat --paging=never'
alias grep='rg'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias rmbin='/usr/bin/rm -iv'
alias find='fd'
alias ..='cd ..'
alias dira='direnv allow'
alias dire='direnv edit .'
alias dird='direnv deny'
alias dirr='direnv reload'
alias tn='tldr --list | fzf --preview "tldr {} | bat -l md --style=plain --color=always" --bind "enter:execute(tldr {} | nvim -c \"set ft=markdown buftype=nofile\" -)"'
