alias rm='trash'
alias restore='trash-restore'
alias ls='eza -l --header --group-directories-first --icons=auto'
alias cat='bat --paging=never'
alias grep='rg'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias rmbin='/usr/bin/rm -iv'
alias find='fd'
alias ..='cd ..'
alias frup='fresh --cmd update'
alias tf='tldr "$(tldr --list | fzf --preview '\''tldr {}'\'')" '
# alias dira='direnv allow'
# alias dire='direnv edit .'
# alias dird='direnv deny'
# alias dirr='direnv reload'
